apiVersion: v1
kind: Pod
metadata:
  name: offensive-pod
  namespace: protected
spec:
  containers:
    - args:
        - sleep
        - "3600"
      image: busybox
      name: offensive-container
  restartPolicy: Always
